Name:           ros-jade-rosserial-client
Version:        0.7.6
Release:        0%{?dist}
Summary:        ROS rosserial_client package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/rosserial_client
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-rosbash
Requires:       ros-jade-rospy
Requires:       ros-jade-rosserial-msgs
Requires:       ros-jade-std-msgs
Requires:       ros-jade-tf
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-rosserial-msgs

%description
Generalized client side source for rosserial.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Wed Mar 01 2017 Paul Bouchier <paul.bouchier@gmail.com> - 0.7.6-0
- Autogenerated by Bloom

* Tue Nov 22 2016 Paul Bouchier <paul.bouchier@gmail.com> - 0.7.5-0
- Autogenerated by Bloom

* Wed Sep 21 2016 Paul Bouchier <paul.bouchier@gmail.com> - 0.7.4-0
- Autogenerated by Bloom

* Fri Aug 05 2016 Paul Bouchier <paul.bouchier@gmail.com> - 0.7.3-0
- Autogenerated by Bloom

* Fri Jul 15 2016 Paul Bouchier <paul.bouchier@gmail.com> - 0.7.2-0
- Autogenerated by Bloom

* Mon Jul 06 2015 Paul Bouchier <paul.bouchier@gmail.com> - 0.7.1-0
- Autogenerated by Bloom

* Thu Apr 23 2015 Paul Bouchier <paul.bouchier@gmail.com> - 0.7.0-0
- Autogenerated by Bloom

