Name:           ros-lunar-rosserial-server
Version:        0.7.7
Release:        0%{?dist}
Summary:        ROS rosserial_server package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lunar-roscpp
Requires:       ros-lunar-rosserial-msgs
Requires:       ros-lunar-rosserial-python
Requires:       ros-lunar-std-msgs
Requires:       ros-lunar-topic-tools
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-rosserial-msgs
BuildRequires:  ros-lunar-std-msgs
BuildRequires:  ros-lunar-topic-tools

%description
A more performance- and stability-oriented server alternative implemented in C++
to rosserial_python.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Wed Nov 29 2017 Mike Purvis <mpurvis@clearpathrobotics.com> - 0.7.7-0
- Autogenerated by Bloom

